### ISSUE TITLE
能否修改选中项的文本样式呢

### ISSUE THREAD

**Issue by FishLyn** [yz1311/react-native-wheel-picker#1]

**Comment by FishLyn** [comment]
能否修改选中项的样式呢？

**Comment by lexguy** [comment]
> _No description provided._

you can try this  
[slidepicker](https://github.com/lexguy/react-native-slidepicker)

**Comment by zhuchuanwu** [comment]
同问

**Comment by yz1311** [comment]
新版本已解决
