### ISSUE TITLE
requireNativeComponent: "WheelCurvedPicker" was not found in the UIManager

### ISSUE THREAD

**Issue by JesseWeb** [yz1311/react-native-wheel-picker#15]
运行环境为安卓，使用expo做构建和项目骨架，遇到了这个问题，好像是expo和wheelpicker之间的问题

**Comment by yz1311** [comment]
不好意思，没看到提醒邮件，这么久才回
expo的环境不太清楚，请看下expo的库的集成方式，这个库android端是有原生代码的,还是不行的话，那可能真的是不兼容expo😂
