### ISSUE TITLE
Warning: PickerIOS has been extracted from react-native core and will be removed in a future release.

### ISSUE THREAD

**Issue by lionel178** [yz1311/react-native-wheel-picker#16]
Warning: PickerIOS has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker

**Comment by yz1311** [comment]
目前的RN版本只是会警告，如果想忽略警告的话，可以直接利用
```
LogBox.ignoreLogs([
    'PickerIOS has been extracted'
]);
```

在RN正式移除PickerIOS组件之前，这个库会改为`react-native-picker`,目前在想兼容的办法

**Comment by lionel178** [comment]
感谢作者~
