### ISSUE TITLE
ios error

### ISSUE THREAD

**Issue by tututututututu** [yz1311/react-native-wheel-picker#19]
`
<RegionPicker
    mode='pca'
    onPickerConfirm={(names, codes) => {}}
     selectedValue={['']}
/>
`
TypeError: wheelData.findIndex is not a function

**Comment by yz1311** [comment]
麻烦看下是否为0.3.2版本，另外试下mode="pc"是否也报错

**Comment by tututututututu** [comment]
@yz1311 一样的  也报错 版本是0.3.2

**Comment by tututututututu** [comment]
for (let index in pickerData) {
                    let wheelData = pickerData[index];
                    //默认取第一个元素
                    wheelSelectedIndexes[index] = 0;
                    let findIndex = wheelData.findIndex(x => x == selectedValue[index]);
                    if (findIndex > 0) {
                        wheelSelectedIndexes[index] = findIndex;
                    }
                    selectedValue[index] = wheelData[wheelSelectedIndexes[index]];
                }


这个循环是把pickerData 当成对象循环了吧

**Comment by tututututututu** [comment]
//设置默认值
                for (let index in pickerData) {
                    let wheelData = pickerData[index];
                    //默认取第一个元素
                    wheelSelectedIndexes[index] = 0;
                    let findIndex = wheelData.findIndex(
                        x => x == selectedValue[index]
                    );
                    if (findIndex > 0) {
                        wheelSelectedIndexes[index] = findIndex;
                    }
                    selectedValue[index] =
                        wheelData[wheelSelectedIndexes[index]];
                }

这里这个index 已经是item了  不是下标

**Comment by yz1311** [comment]
@tututututututu 这里用的for..in，并不是for...of,作用就是取index

**Comment by yz1311** [comment]
能不能帮忙看下报错的时候，wheelData是个什么数据？我自己调试mode为pc或者pca没法复现这个问题

**Comment by tututututututu** [comment]
![bugerr](https://user-images.githubusercontent.com/16113734/115526465-a6291f00-a2c2-11eb-9166-f4c30cad8c7a.png)

**Comment by tututututututu** [comment]
Array.prototype.remove = function(val) {
    let index = this.indexOf(val);
    if (index > -1) {
        this.splice(index, 1);
    }
};


因为我项目里面增加了 这个方法 导致的 😁
