### ISSUE TITLE
部分手机出现默认时间选中错误兼容问题

### ISSUE THREAD

**Issue by wywuyou** [yz1311/react-native-wheel-picker#27]
![image](https://user-images.githubusercontent.com/59722083/119597235-37843780-be13-11eb-9df6-7180678f3f35.png)

实际打印出的数据是2021，但是选中效果是2014，不知可否麻烦看一下原因

RN版本0.61.5

**Comment by yz1311** [comment]
1.同样的代码在不同手机效果不一样吗？
2.给的默认值是多少？
3.是显示的2014年，但是最终获取的值是2021？

**Comment by wywuyou** [comment]
> 1.同样的代码在不同手机效果不一样吗？
> 2.给的预设值是多少？
> 3.是显示的2014年，但是最终获取的值是2021？

1.是的，具体可以参考OPPO、模拟器；
2.默认值给的是new Date()；
3.是的，打印出来的selectedDateArray是['2021年', '05月']

**Comment by yz1311** [comment]
麻烦将默认值去掉看下效果？另外在什么模拟器上会出问题，我好重现一下

**Comment by wywuyou** [comment]
> 麻烦将默认值去掉看下效果？另外在什么模拟器上会出问题，我好重现一下

我尝试过只展示一个空的DatePicker组件，效果是一致的，但是第一天在对接的过程中是正常的，第二个就出现了这个问题，目前使用的夜神模拟器和逍游模拟器都出现了相同的问题

**Comment by wywuyou** [comment]
> 麻烦将默认值去掉看下效果？另外在什么模拟器上会出问题，我好重现一下

![image](https://user-images.githubusercontent.com/59722083/119600084-de1f0700-be18-11eb-95d4-d416e0f2c074.png)

这是空的DatePicker组件效果

**Comment by yz1311** [comment]
好，我只能晚上看下，最迟明天上午给你回复

**Comment by wywuyou** [comment]
> 看下，最迟明天上午给你回复

嗯嗯 好的 感谢

**Comment by yz1311** [comment]
0.3.4版本已解决

**Comment by wywuyou** [comment]
> 0.3.4版本已解决

嗯嗯 好的 万分感谢
