### ISSUE TITLE
是否有计划分离出相对纯净的版本？

### ISSUE THREAD

**Issue by vvizden** [yz1311/react-native-wheel-picker#28]
你好，我看了好多类似的组件，看了你掘金的文章，这个组件很棒！请问是否有计划分离出一个不依赖 Moment 和 Modal 的相对纯净的版本，因为我可能偏向选择 dayjs，然后基于你的组件自行封装日期选择组件。

**Comment by yz1311** [comment]
react-native-modal这个库虽然依赖于RN的Modal组件，但是是一个纯粹的js库，只是对Modal组件的功能进行了强化，我认为是RN开发是一个必装的库。
moment这个库，理论上是可以直接替换为dayjs库的，但是考虑到需要增减库所以没有动

rn开发其实没必要像web端那样在意这种功能性包的大小，毕竟你随便引入一个带原生库的包带来的体积增长大得多

1.如果是考虑包的大小，将moment替换为dayjs对最终安装包的大小影响非常小

2.至于功能，你如果需要自己封装组件，可以直接将dayjs的引入改为moment即可，我碰到的绝大部分情况都是通用的

**Comment by vvizden** [comment]
> react-native-modal这个库虽然依赖于RN的Modal组件，但是是一个纯粹的js库，只是对Modal组件的功能进行了强化，我认为是RN开发是一个必装的库。
> moment这个库，理论上是可以直接替换为dayjs库的，但是考虑到需要增减库所以没有动
> 
> rn开发其实没必要像web端那样在意这种功能性包的大小，毕竟你随便引入一个带原生库的包带来的体积增长大得多
> 
> 1.如果是考虑包的大小，将moment替换为dayjs对最终安装包的大小影响非常小
> 
> 2.至于功能，你如果需要自己封装组件，可以直接将dayjs的引入改为moment即可，我碰到的绝大部分情况都是通用的

你说的很有道理，可能是我RN的开发经验有限，目前只用到RN提供的Modal组件，至于依赖包的大小，的确是Web开发的习惯，而且我项目中已经有地方使用的 dayjs，虽然理论上和 moment 是可以无缝切换，但是我不太想动以前的代码，我这边已经尝试使用 patch-package，将你组件中的 moment 替换为 dayjs，README 中的示例已经成功呈现，感谢回答！
