### ISSUE TITLE
能否开放PickerItem的样式设置

### ISSUE THREAD

**Issue by fuavix** [yz1311/react-native-wheel-picker#29]
<PickerItem
        key={itemIndex}
        value={itemIndex}
        label={value.toString()}
/>
WheelCurvedPicker之下有
    textColor: ColorPropType,
    textSize: PropTypes.number,
    itemStyle: PropTypes.object,
    itemSpace: PropTypes.number....等等

**Comment by RainFalling1** [comment]
@fuavix IOS的样式是否可以修改

**Comment by yz1311** [comment]
@fuavix @RainFalling1  不好意思没看到这个问题，这几个属性其实已经暴露出来了，在android端其实可以直接使用，只是没有在ts定义中写上
其中textColor、textSize是合并到itemStyle中的，ios端也支持，其他的一些属性只有android端支持

https://github.com/react-native-picker/picker
目前ios端的代码是根据这个来了，所以暴露出来的属性都是两端同时支持的属性

**Comment by RainFalling1** [comment]
@fuavix 多谢你的回答🙏，刚尝试了下，去修改源码可以做到一些修改，只是方法比较笨，希望作者早点更新。
![image](https://user-images.githubusercontent.com/51017002/122874461-98952180-d365-11eb-943e-b4f594973b81.png)

**Comment by RainFalling1** [comment]
@yz1311 谢谢作者回复🙏，我已经知道怎么改了😂。封装得已经很好了，希望再完善一下样式设置和文档👍👍👍
