### ISSUE TITLE
DatePicker 性能如何优化 

### ISSUE THREAD

**Issue by 289420843** [yz1311/react-native-wheel-picker#3]
低端设备上运行开启DatePicker mode = date min 1950-01-01  5秒才能打开
测试设备：华为C5
有办法优化吗？

**Comment by yz1311** [comment]
如果所需的时间范围不需要那么大，可以将minDate和maxDate的范围改小一点，加载的数据量小会快些

DatePicker这个组件这周优化下，将数据的初始化改为异步应该会好点

**Comment by 289420843** [comment]
用于选择出生日期，范围不能缩小了，希望尽快优化
非常感谢你

**Comment by yz1311** [comment]
@289420843   可以试下最新的0.2.0版本，DatePicker的性能已经优化了
