### ISSUE TITLE
itemstyle 不管怎么设置选中时候的颜色都是黑色

### ISSUE THREAD

**Issue by zhuchuanwu** [yz1311/react-native-wheel-picker#31]
itemstyle 不管怎么设置选中时候的颜色都是黑色

**Comment by HuXin957** [comment]
老哥，itemstyle的问题ok了吗？

**Comment by yz1311** [comment]
![QQ20210831-204743](https://user-images.githubusercontent.com/9854019/131522738-964e316d-e8e2-4dbd-9588-04b5543fda8f.png)
![WechatIMG50](https://user-images.githubusercontent.com/9854019/131522752-5f9b4acb-fd59-4efc-b29f-3f82bc576794.jpeg)
@HuXin957 @zhuchuanwu  已经修复，最新版0.3.6

**Comment by HuXin957** [comment]
> ![QQ20210831-204743](https://user-images.githubusercontent.com/9854019/131522738-964e316d-e8e2-4dbd-9588-04b5543fda8f.png)
> ![WechatIMG50](https://user-images.githubusercontent.com/9854019/131522752-5f9b4acb-fd59-4efc-b29f-3f82bc576794.jpeg)
> @HuXin957 @zhuchuanwu 已经修复，最新版0.3.6

牛批，我滴宝贝儿
