### ISSUE TITLE
DatePicker组件没有接收itemStyle，导致不能改字体颜色

### ISSUE THREAD

**Issue by HuXin957** [yz1311/react-native-wheel-picker#35]
时间选择DatePicker这个组件，没有接收itemstyle这个属性，能帮忙加上吗，老哥。
![image](https://user-images.githubusercontent.com/58537144/131636231-17f60989-eddd-42d9-a926-79c9a2a7cc52.png)

**Comment by yz1311** [comment]
0.3.7已修复

**Comment by yz1311** [comment]
先试下   0.3.8-beta1   版本，没问题的话，我发布正式版本

**Comment by HuXin957** [comment]
> 试下 0.3.8 版本

真神速啊，感谢
