### ISSUE TITLE
直接在工具里面报Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2

### ISSUE THREAD

**Issue by santant** [yz1311/react-native-wheel-picker#39]
Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2
Show in Project Structure dialog
Affected Modules: yz1311_react-native-wheel-picker

**Comment by santant** [comment]
0.65直接下载下来安卓报错的

**Comment by Encoboy** [comment]
react-native 0.66.3
android studio :2020.3.1
也是一样的问题：Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2

**Comment by yz1311** [comment]
> react-native 0.66.3 android studio :2020.3.1 也是一样的问题：Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2

将项目的仓库从Jcenter改到mavenCentral或者直接淘宝的仓库试下，jcenter已经过期了

**Comment by montilloo** [comment]
> > react-native 0.66.3 android studio :2020.3.1 也是一样的问题：Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2
> 
> 将项目的仓库从Jcenter改到mavenCentral或者直接淘宝的仓库试下，jcenter已经过期了

同样的问题，前端同学看不懂怎么更换淘宝仓库

**Comment by howieyi** [comment]
> 



> > > react-native 0.66.3 android studio :2020.3.1 也是一样的问题：Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2
> > 
> > 
> > 将项目的仓库从Jcenter改到mavenCentral或者直接淘宝的仓库试下，jcenter已经过期了
> 
> 同样的问题，前端同学看不懂怎么更换淘宝仓库



> > > react-native 0.66.3 android studio :2020.3.1 也是一样的问题：Failed to resolve: cn.aigestudio.wheelpicker:WheelPicker:1.1.2
> > 
> > 
> > 将项目的仓库从Jcenter改到mavenCentral或者直接淘宝的仓库试下，jcenter已经过期了
> 
> 同样的问题，前端同学看不懂怎么更换淘宝仓库


`maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
`
