### ISSUE TITLE
wheel

### ISSUE THREAD

**Issue by meiqi1992** [yz1311/react-native-wheel-picker#4]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/15257730/91308015-43d65800-e7e1-11ea-91ea-10a6a27d5e06.png">

省市区选择 出现这个错误：
以下是代码
                        <RegionPicker
                            onPickerConfirm={(names, codes) => {
                                console.log(names)
                                console.log(codes)
                                //names: ["上海市", "市辖区", "黄浦区"]
                                //codes: ["31", "3101", "310101"]
                            }}
                            selectedValue={''} 
                            />

**Comment by meiqi1992** [comment]
RN 0.63.2

**Comment by yz1311** [comment]
![image](https://user-images.githubusercontent.com/9854019/91309148-d4616800-e7e2-11ea-897c-af5bfb7e1b96.png)

库用的什么版本？我刚试了下，直接拷贝你的代码，是没有报错的

**Comment by meiqi1992** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/15257730/91310333-530ad500-e7e4-11ea-9fd2-64b0d24fb497.png">
您好～我就直接用了说明文档的安装命令，然后装了这两库

**Comment by meiqi1992** [comment]
我用日历的DatePicker 没问题，可以弹出来

**Comment by yz1311** [comment]
😅还是没有复现，您看试下直接从外部引入这个文件试下
```
<RegionPicker
            data={require('./pca-code.json')}
            onPickerConfirm={(names, codes)=>{
              //names: ["上海市", "市辖区", "黄浦区"]
              //codes: ["31", "3101", "310101"]
            }}
            selectedValue={['']} />
```

pca-code.json文件可以从`node_modules/@yz1311/react-native-wheel-picker/src/resource/pca-code.json ` 找到复制过来就行了，如果还是不行的，有空的话看能否整个复现的demo

**Comment by meiqi1992** [comment]
谢谢，从外部引入还是一样的错～

**Comment by yz1311** [comment]
@meiqi1992 如果有空,烦请试下 0.2.0版本
