### ISSUE TITLE
想问一下这个是什么问题 ios能使用

### ISSUE THREAD

**Issue by yushuangxu** [yz1311/react-native-wheel-picker#48]
![EE3E4317-601A-4D8D-962E-7FC33EE6CF0E](https://user-images.githubusercontent.com/55570020/153990152-aeb598f9-122e-413b-93f7-594e1c1758d3.png)

**Comment by yz1311** [comment]
数据有问题，最好就是字符串数组

**Comment by yushuangxu** [comment]
我用的你那个时间组件 还是不行我没有修改里面的数据

**Comment by yushuangxu** [comment]
> 数据有问题，最好就是字符串数组

我用的就是你封装的那个时间组件 但是还是不可以使用

**Comment by yz1311** [comment]
调用方法发下，我晚上看下

**Comment by yushuangxu** [comment]
> 调用方法发下，我晚上看下

好像可以了，我把你那个WheelCurvedPicker.android文件里面的_stateFromProps这个方法里面的items.push({ value: String(child.props.value), label: child.props.label }); value: String(child.props.value),改成了 value:child.props.value

**Comment by yz1311** [comment]
WheelCurvedPicker.android  是针对于android的文件，照理说不应该对ios环境其作用，暂时无解，先关闭了
