### ISSUE TITLE
想问一下大佬安卓真机一列里面滑动次数很多,那一列突然消失几秒钟,或者有时候会突然到一列的最底部。大佬有没有遇见过。

### ISSUE THREAD

**Issue by yushuangxu** [yz1311/react-native-wheel-picker#49]

**Comment by yz1311** [comment]
是不是滚动的过快？

**Comment by yushuangxu** [comment]
> 是不是滚动的过快？

就是手一直不停的滑动一列 有时候会整列都消失 或者有时候会直接跳到底部

**Comment by yz1311** [comment]
> > 是不是滚动的过快？
> 
> 就是手一直不停的滑动一列 有时候会整列都消失 或者有时候会直接跳到底部

 那这个应该算正常情况，滑动太快，来不及渲染，你感觉跳动到底部只是因为在底部不动了，然后上面的内容才渲染出现的效果
