### ISSUE TITLE
pickerIos 已经被删除

### ISSUE THREAD

**Issue by JonsonHI** [yz1311/react-native-wheel-picker#51]
Invariant Violation: PickerIOS has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker 

iOS这边的 picker 已经 在react-native 中移除掉了    请问该如何处理

**Comment by yz1311** [comment]
这个库已经将ios的picker代码放进去了，所以不必依赖于@react-native-picker/picker

**Comment by JonsonHI** [comment]
刚看了源码 确实 放到 iOS文件里了   不好意思 我的问题  ,   大意了
