### ISSUE TITLE
目前没有支持RN web

### ISSUE THREAD

**Issue by yatessss** [yz1311/react-native-wheel-picker#59]
目前只有原生组件，运行RN web时会报错

**Comment by yz1311** [comment]
看到你的commit，我这边没有用过react-native-web😅，你这边测试好的话我合并发一个新版本

**Comment by yz1311** [comment]
有个问题请教下，纯RN的项目用react-native-web改成web的话，改动量大吗?

**Comment by yatessss** [comment]
@yz1311 你好 我已支持了web，提了PR，如果可以的话麻烦合并下 发个包，我本地再接入试试

**Comment by yatessss** [comment]
> 有个问题请教下，纯RN的项目用react-native-web改成web的话，改动量大吗?

如果组件都是基于RN实现的 改动量不算太大，如果组件有很多原生的 就比较麻烦了，具体PR中我列了几个参考项目，可以参考这几个项目尝试接入

**Comment by yatessss** [comment]
> 



> 看到你的commit，我这边没有用过react-native-web😅，你这边测试好的话我合并发一个新版本

我本地尝试直接修改npm包的内容后是可以的，有个问题是本身项目没有使用构建工具所以并不能使用tsx 只能用js了

**Comment by yz1311** [comment]
> 

好，我合并下，发布npm包里面会包含js文件的

**Comment by yatessss** [comment]
> > 
> 
> 好，我合并下，发布npm包里面会包含js文件的

好的，原来的react-native-wheel-picker作者没有再支持了，看到这个项目真不错~  感谢感谢~

**Comment by yz1311** [comment]
@yatessss   0.4.0-beta1  试下这个

**Comment by yatessss** [comment]
> @yatessss 0.4.0-beta1 试下这个

好的我试试，加下你微信吧 方便沟通

**Comment by yz1311** [comment]
就是yz1311

**Comment by yatessss** [comment]
> 就是yz1311

好的

**Comment by yatessss** [comment]
#60
