### ISSUE TITLE
regionPicker data.json

### ISSUE THREAD

**Issue by Benjamin148** [yz1311/react-native-wheel-picker#6]
Can you provide it in read me?

**Comment by yz1311** [comment]
you can find it here:

https://github.com/yz1311/react-native-wheel-picker/blob/master/src/resource/pca-code.json

the data is from this project:
https://github.com/modood/Administrative-divisions-of-China

Currently  `regionPicker` support province/city/area mode for regular use, but  this library is easy to extend.

**Comment by yz1311** [comment]
I have update readme.MD file, but it is Chinese.If you need any help, just tell me .

照理说用regionPicker这个组件不应该不懂中文🤔
