### ISSUE TITLE
DateRangePicker 无法获取到选中值

### ISSUE THREAD

**Issue by 289420843** [yz1311/react-native-wheel-picker#9]
onValueChange  onPickerConfirm 均无法正确返回选择日期

**Comment by yz1311** [comment]
😌 又出问题了，明早前会发布一个新版本，我重新整理下这个组件的Api

**Comment by yz1311** [comment]
😌 又出问题了，明早前会发布一个新版本，我重新整理下这个组件的Api

这周会全面梳理下这个库的api并完善一个全面的demo出来，经常出问题太不应该了😞

**Comment by yz1311** [comment]
@289420843  0.2.3版本已经修复该问题，感谢反馈🤝
